name = "e-consultation"
main = "functions/index.js"
compatibility_date = "2024-05-01"

# Menyajikan file statis dari folder public
[assets]
directory = "./public"

# Koneksi ke Cloudflare KV (database)
[[kv_namespaces]]
binding = "DB"
id = "GANTI_DENGAN_ID_KV_ANDA"
preview_id = "GANTI_DENGAN_PREVIEW_ID_KV_ANDA"
[vars]
ACCOUNTS_JSON = '{"FormConsulting2027":{"password":"ConsulInspektorat2027","role":"Form"},"AuditorA.Muda":{"password":"Auditor.2026Amuda","role":"Auditor"},"PPUPD.AMuda":{"password":"PPUPD,2026A.muda","role":"PPUPD"},"IrbanI":{"password":"Irbanwi1","role":"Irban I"},"IrbanII":{"password":"Irbanwil2","role":"Irban II"},"IrbanIII":{"password":"Irbanwil3","role":"Irban III"},"Inspekturmahulu":{"password":"ItdaMahulu2026","role":"Inspektur"}}'
compatibility_flags = ["nodejs_compat"]
